---
- name: Un playbook muy muy sencillo
  # A quienes se les va a operar 
  hosts: web
  tasks:
    - name: Dame un mensaje camilooooo
      ansible.builtin.debug:
        msg: "Bienvenido al mundo de Ansible"
